Babloos/Controllers/OrderController.cs
using ACATrack.Helpers;
using Babloos.Helpers;
using Babloos.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Babloos.Controllers
{
    public class OrderController : Controller
    {
        private BabloosEntities db = new BabloosEntities();
        //
        // GET: /Order/
        public ActionResult Index()
        {
            var menu = db.Menus.Where(p=> p.IsActive).ToList();
            var menuitems = db.MenuItems.Where(p=> p.IsActive).ToList();

            AllMenu allmenu = new AllMenu();

            allmenu.menuList = menu;
            allmenu.menuitemList = menuitems;

            return View(allmenu);
        }

        public String AddToCart(int itemId, int quantity)
        {
            return JsonConvert.SerializeObject(SessionHelper.Cart(itemId, quantity));
        }

        public String RemoveItemCart(int itemId)
        {
            return JsonConvert.SerializeObject(SessionHelper.Remove("CART", itemId));
        }

        public String GetToCart()
        {
            return JsonConvert.SerializeObject(SessionHelper.Read<Order>("CART"));
        }

        public ActionResult Checkout()
        {
            Order order = SessionHelper.Read<Order>("CART");
            return View(order);
        }

        [HttpPost]
        public ActionResult Checkout([Bind(Include = "Id,UserId,Email,Title,FirstName,LastName,Address1,Address2,City,TotalAmount,OrderDate,DeliveryOption,DeliveryDate,Instructions,OrderStatus,MobileNumber")]Order order)
        {
            if(ModelState.IsValid) {
                // SAVE ORDER
                db.Orders.Add(order);
                db.SaveChanges();
            }
            else
            {
                return RedirectToAction("Index");
            }
            Order sessionOrder = SessionHelper.Read<Order>("CART"); // READ ORDER ITEMS IN CART
            OrderDetail orderdetails = null;
            List<OrderDetail> orderDetailList = new List<OrderDetail>();

            // SAVE ORDER DETAILS
            foreach (var item in sessionOrder.OrderDetails.ToList())
            {
                orderdetails = new OrderDetail{
                    OrderId = order.Id,
                    MenuItemId = item.MenuItemId,
                    Title = item.Title,
                    Quantity = item.Quantity,
                    Price = item.Price,
                    Amount = item.Amount,
                    OrderDate = DateTime.Now,
                    DeliveryDate = DateTime.Now
                };
                db.OrderDetails.Add(orderdetails);
                db.SaveChanges();
                orderDetailList.Add(orderdetails);
                SessionHelper.Remove("CART", item.MenuItemId);
            }

            EmailManager.SendOrder("to-email", "Team", orderDetailList, order);
            return RedirectToAction("Successful");
        }

        public ActionResult Successful()
        {
            return View();
        }
	}
}

Babloos/Controllers/UserInfoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Babloos.Models;
using Babloos.Helpers;

namespace Babloos.Controllers
{
    public class UserInfoController : Controller
    {
        private BabloosEntities db = new BabloosEntities();

        // GET: /UserInfo/
        public ActionResult Index()
        {
            return View(db.UserInfoes.ToList());
        }

        // GET: /UserInfo/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserInfo userinfo = db.UserInfoes.Find(id);
            if (userinfo == null)
            {
                return HttpNotFound();
            }
            return View(userinfo);
        }

        // GET: /UserInfo/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /UserInfo/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,Title,FirstName,LastName,Phone,AlternativePhone,Address1,Address2,City,EmailAddress,Password,IsActive,CreationDate,UserType")] UserInfo userinfo)
        {
            if (ModelState.IsValid)
            {
                userinfo.IsActive = true;
                userinfo.CreationDate = DateTime.Now;
                userinfo.UserType = 1;

                db.UserInfoes.Add(userinfo);
                db.SaveChanges();
                return RedirectToAction("Login");
            }

            return View(userinfo);
        }

        // GET: /UserInfo/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserInfo userinfo = db.UserInfoes.Find(id);
            if (userinfo == null)
            {
                return HttpNotFound();
            }
            return View(userinfo);
        }

        // POST: /UserInfo/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Title,FirstName,LastName,Phone,AlternativePhone,Address1,Address2,City,EmailAddress,Password,IsActive,CreationDate,UserType")] UserInfo userinfo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userinfo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userinfo);
        }

        // GET: /UserInfo/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserInfo userinfo = db.UserInfoes.Find(id);
            if (userinfo == null)
            {
                return HttpNotFound();
            }
            return View(userinfo);
        }

        // POST: /UserInfo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            UserInfo userinfo = db.UserInfoes.Find(id);
            db.UserInfoes.Remove(userinfo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login([Bind(Include = "EmailAddress,Password")] UserInfo userinfo)
        {
            UserInfo user = db.UserInfoes.FirstOrDefault(u => (u.EmailAddress == userinfo.EmailAddress || u.Phone == userinfo.EmailAddress) && u.Password == userinfo.Password);
            if (user != null)
            {
                SessionHelper.Login("CART", user.Id);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Message = "Invalid UserName or Password!";
                return View(userinfo);
            }
        }

        public ActionResult Logoff()
        {
            SessionHelper.logOff("CART");
            return RedirectToAction("Index", "Home");
        }

        public ActionResult ChangePassword()
        {
            Order order = SessionHelper.Read<Order>("CART");
            ViewBag.UserId = order.UserId; 
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePassword([Bind(Include = "Id,Password")] UserInfo userinfo, String ConfirmPassword, String OldPassword)
        {
            UserInfo user = db.UserInfoes.Find(userinfo.Id);
            if(user.Password == OldPassword && userinfo.Password == ConfirmPassword) {
                user.Password = userinfo.Password;
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                ViewBag.MsgSuccess = "Change Password Successfully!";
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.MsgWrong = "Some thing wrong. Try again.";
                Order order = SessionHelper.Read<Order>("CART");
                ViewBag.UserId = order.UserId;
                return View();
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Babloos/Views/Shared/_Layout.cshtml
@{
    String tab = Request.ApplicationPath;
    Babloos.Models.Order order = Babloos.Helpers.SessionHelper.Read<Babloos.Models.Order>("CART");
    
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Babloo's Dine Inn &amp; Take Away - A fast food restaurant in Jhang, Punjab, Pakistan with healthy and hygienic food.">
    <meta name="keywords" content="Fast Food in Jhang,Best Pizza in Jhang,Takeaway in Jhang,restaurant in Jhang,Home Delivery in Jhang,Family Environment in Jhang, Air conditioned environment,Coffee shop in Jhang">
    <meta name="author" content="Babloo's Dine Inn &amp; Take Away">
    <title>Babloo's Dine Inn &amp; Take Away</title>
    <!-- You can use open graph tags to customize link previews.
    Learn more: https://developers.facebook.com/docs/sharing/webmasters -->
    <meta property="og:url" content="http://www.babloos.pk" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Babloo's Dine Inn &amp; Take Away" />
    <meta property="og:description" content="Babloo's Dine Inn &amp; Take Away - A fast food restaurant with healthy and hygienic food. Fast Food in Jhang, Best Pizza in Jhang" />
    <meta property="og:image" content="http://www.babloos.pk/Images/Babloos.png" />
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    <script>
        function activePageMenu(n) {
            debugger;
            var li = $("#main_menu li").eq(n - 1);
            li.css("background", "white");
            li.children().css("color", "red");
        }
    </script>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-67877546-1', 'auto');
        ga('send', 'pageview');

    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top menu-border">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand menu-logo">
                    <img src="/Images/logo.png" class="img-responsive" alt="Babloo's" height="50" />
                </a>
            </div>
            <div class="navbar-collapse collapse menu-font">
                @*<ul class="nav navbar-nav navbar-right" id="cart_nav">
                    <li id="itemQuantity">0</li>
                    <li id="cart">
                        <a>Cart</a>
                        <ul>
                            <li class="cart"></li>
                            <li><button class="btn btn-danger btn_checkout" onclick="location.href = '/Order/Checkout'">Checkout me!</button></li>
                        </ul>
                    </li>
                </ul>*@
                @*@Html.Partial("_LoginPartial")*@
                
                <ul class="nav navbar-nav navbar-right" id="main_menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Order Now", "Index", "Order")</li>
                    <li>@Html.ActionLink("Checkout", "Checkout", "Order")</li>
                    <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>
                    @*@if(order.UserId != null) {
                        <li>@Html.ActionLink("Welcome! " + order.FirstName, "ChangePassword", "UserInfo")</li>
                        <li>@Html.ActionLink("Logoff", "Logoff", "UserInfo")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Register", "Create", "UserInfo")</li>
                        <li>@Html.ActionLink("Log in", "Login", "UserInfo")</li>
                    }*@
                    <li>
                        <ul class="nav navbar-nav navbar-right" id="cart_nav">
                            <li id="itemQuantity">0</li>
                            <li id="cart" dir="rtl">
                                <a>Cart</a>
                                <ul>
                                    <li class="cart"></li>
                                    <li><button class="btn btn-danger btn_checkout" onclick="location.href = '/Order/Checkout'">!Checkout me</button></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    <div class="container-fluid footer-style">
        <footer>
            <p>All rights reserved. &copy; @DateTime.Now.Year - Babloo's Dine Inn &amp; Takeaway</p>
        </footer>
    </div>
    <script>
        $.ajax({
            url: "/Order/GetToCart",
            type: "POST",
            success: function (result) {
                fillCart(result);
            }
        });

        $(".add_to_cart").click(function () {
            var itemid = $(this).next().val();
            var quantity = $(this).parent().parent().find(".quentity").val();

            $.ajax({
                url: "/Order/AddToCart",
                type: "POST",
                data: { itemId: itemid, quantity: quantity },
                success: function (result) {
                    fillCart(result);
                }
            });
        });

        $(".quentity").keypress(function (e) {
            if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
                return false;
            }
        });

        $("#cart a").click(function () {
            $("#cart ul").slideToggle();
        });
        $(".body-content, footer").click(function () {
            $("#cart ul").slideUp();
        });

        
        

        var color = ["#FFFFFF", "#FFFF99", "#B2FF99", "#CCFFFF", "#FFCCFF", "#D1FFFF", "#FFB2B2", "#E6CC80"]

        rainbow(0);

        function rainbow(i) {
            var index = i % 8;
            $("#cart").css("background", color[index]);
            i = i + 1;
            setTimeout("rainbow("+i+")", 1000);
        }

        function removeCheck(id) {
            $.ajax({
                url: "/Order/RemoveItemCart",
                type: "POST",
                data: { itemId: id },
                success: function (result) {
                    fillCart(result);
                }
            });
        }

        function fillCart(data) {
            var items = JSON.parse(data);
            $(".cartItem").html("");
            var numberOfItem = 0;
            var totalAmount = 0;
            var tbody = '';
            var table = '';
            if (items.OrderDetails != "") {
                $.each(items.OrderDetails, function (index, order) {
                    tbody = tbody +
                         "<tr>" +
                         "<td><button class='btn btn-danger btn-sm checkout_remove' id='" + order.MenuItemId + "' onclick='removeCheck(this.id)'><span class='glyphicon glyphicon-remove-sign pull-left'></span> <span class='hidden-xs pull-right' style='margin-left:2px;'>Remove</span></button>" +
                         "<td>Rs." + order.Amount + "</td>" +
                         "<td>Rs." + order.Price + "</td>" +
                         "<td>" + order.Quantity + "</td>" +
                         "<td>" + order.Title + "</td>" +
                         "<td><img src='../" + order.ImagePath + "' height='50'></td>" +
                         "</tr>";
                    numberOfItem = numberOfItem + 1;
                    totalAmount = totalAmount + Number(order.Amount);
                });
                $(".btn_checkout").prop("disabled", false);
            } else {
                tbody = "<tr><td colspan='6' class='text-center'>No item in cart.</td></tr>";
                $(".btn_checkout").prop("disabled", true);
            }

            table = '<table class="table table-responsive">' +
                    '<thead>' +
                    '<tr>' +
                    '<td>Action</td>' +
                    '<td>Amount</td>' +
                    '<td>Unit Price</td>' +
                    '<td>Qty</td>' +
                    '<td>Name</td>' +
                    '<td></td>' +
                    '</tr>' +
                    '</thead>' +
                    '<tbody class="cartItem">' + tbody + '</tbody>' +
                    '<tfoot><tr><td colspan="4">Total Amoumt Rs.<td><td>'+totalAmount+'</td></tr></tfoot>' +
                    '</table>';

            $(".cart").html(table);
            $("#itemQuantity").html(numberOfItem);
            $("#TotalAmount").val(totalAmount);
        }
    </script>
    
</body>
</html>